#%RAML 1.0
title: search

types:
  schemaVariable : !include Schemas/newsdataType.raml

/search:
  get:
    queryParameters:
      keywords:
        type: string
        minLength: 3
        maxLength: 10
    responses:
      200:
        body:
          application/json:
            example: !include   examples/searchexample.raml            


/news:
  post:
    queryParameters:
      country:
        required: false
    body:
      application/json:
        type: schemaVariable[]
    responses:
      201:
        body:
          application/json:
            example:
              {"Indian News": "Breaking NEWS....."}




